name: Build and Deploy to ROSA

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build --prod

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/angular-app:latest .
        docker push ghcr.io/${{ github.repository_owner }}/angular-app:latest

    # - name: Install OpenShift CLI
    #   run: |
    #     curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
    #     tar -xzf openshift-client-linux.tar.gz
    #     sudo mv oc /usr/local/bin

    # - name: Login to OpenShift
    #   run: |
    #     oc login --token=${{ secrets.ROSA_TOKEN }} --server=${{ secrets.ROSA_SERVER }}

    # - name: Deploy to ROSA
    #   run: |
    #     oc apply -f deployment.yaml
    #     oc apply -f service.yaml
